[tool.poetry]
name = "tallermk"
version = "0.1.0"
description = "taller mecanido diseñado en DUOC"
authors = ["Williams Diaz Santander"]
readme = "README.md"
poetry = "1.7.1"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
