databases:
  - name: tallermk
    databaseName: tallermk
    user: tallermk

services:
  - type: web
    name: tallermk
    runtime: python
    buildCommand: "./build.sh"
    tartCommand: "gunicorn tallermk.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tallermk
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4