# Generated by Django 4.2.1 on 2023-06-01 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=80)),
                ('fecha', models.DateField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appweb.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=80)),
                ('fecha', models.DateField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appweb.usuario')),
                ('trabajos_autorizados', models.ManyToManyField(related_name='trabajos_autorizados', to='appweb.mecanico')),
            ],
        ),
    ]
