# Generated by Django 4.2.1 on 2023-06-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_rename_fecha_mecanico_fecha_nacimiento_mecanico_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanico',
            name='descripcion',
            field=models.CharField(default='0', max_length=80),
        ),
    ]
