# Generated by Django 4.2.1 on 2023-06-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0007_administrador_motivo_rechazo_trabajo_autorizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='imagenes',
            field=models.ImageField(null=True, upload_to='Mecanico'),
        ),
    ]
