# Generated by Django 4.2.1 on 2023-07-03 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appweb', '0009_alter_trabajo_imagenes'),  # Reemplaza '0011_nombre_migracion_anterior' por el nombre de la migración anterior
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
