# Generated by Django 4.2.1 on 2023-07-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0012_trabajo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='trabajos_autorizados',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='categoria',
            field=models.CharField(choices=[('Mantencion', 'Mantencion'), ('Reparacion', 'Reparacion'), ('Diagnostico', 'Diagnostico')], default='Mantencion', max_length=20),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='nombre',
            field=models.CharField(max_length=70),
        ),
    ]
