# Generated by Django 4.2.1 on 2023-07-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0013_remove_administrador_trabajos_autorizados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('segundo_nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=70)),
                ('segundo_apellido', models.CharField(max_length=70)),
                ('telefono', models.IntegerField(max_length=25)),
                ('email', models.EmailField(max_length=60)),
                ('foto', models.ImageField(null=True, upload_to='Curriculums')),
                ('experiencia', models.CharField(max_length=300)),
            ],
        ),
    ]
