# Generated by Django 4.2.1 on 2023-07-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0014_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='telefono',
        ),
    ]
