# Generated by Django 4.2.1 on 2023-07-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0016_alter_curriculum_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='especialidad',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
