# Generated by Django 4.2.1 on 2023-07-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0018_remove_mecanico_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='cargo',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
