# Generated by Django 4.2.1 on 2023-07-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0019_remove_administrador_cargo_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
