# Generated by Django 4.2.1 on 2023-07-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0020_curriculum_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='numero_telefono',
            field=models.IntegerField(null=True),
        ),
    ]
