# Generated by Django 4.2.1 on 2023-07-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0021_curriculum_numero_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='experiencia',
            field=models.TextField(max_length=1000),
        ),
    ]
