# Generated by Django 4.2.1 on 2023-07-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0022_alter_curriculum_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='rut',
            field=models.CharField(default='1-0', max_length=70),
        ),
    ]
